export default {
    GENERATE_DESCENDANTS_OF_NODE: 'GENERATE_DESCENDANTS_OF_NODE',
    MOVE_UP: 'MOVE_UP',
    MOVE_DOWN: 'MOVE_DOWN',
    MOVE_LEFT: 'MOVE_LEFT',
    MOVE_RIGHT: 'MOVE_RIGHT',
    NAV_TOGGLE: 'NAV_TOGGLE',
    SET_OUTLINE_TREE_NODE: 'SET_OUTLINE_TREE_NODE',
    SET_OUTLINE_TREE_CURRENT_NODE: 'SET_OUTLINE_TREE_CURRENT_NODE',
    UPDATE_CHARACTERS: 'UPDATE_CHARACTERS'
};