export default {
    GENERATE_DESCENDANTS_OF_NODE: 'GENERATE_DESCENDANTS_OF_NODE',
    NAV_TOGGLE: 'NAV_TOGGLE',
    SET_OUTLINE_TREE_NODE: 'SET_OUTLINE_TREE_NODE',
    SET_OUTLINE_TREE_CURRENT_NODE: 'SET_OUTLINE_TREE_CURRENT_NODE'
};