export default {
    DANGEROUSLY_RESET_OUTLINE_TREE: 'DANGEROUSLY_RESET_OUTLINE_TREE',
    GENERATE_DESCENDANTS_OF_NODE: 'GENERATE_DESCENDANTS_OF_NODE',
    TOGGLE_LAYOUT_OVERLAY: 'TOGGLE_LAYOUT_OVERLAY',
    MOVE_UP: 'MOVE_UP',
    MOVE_DOWN: 'MOVE_DOWN',
    MOVE_LEFT: 'MOVE_LEFT',
    MOVE_RIGHT: 'MOVE_RIGHT',
    NAV_TOGGLE: 'NAV_TOGGLE',
    NAV_ASIDE_MOBILE_TOGGLE: 'NAV_ASIDE_MOBILE_TOGGLE',
    SET_OUTLINE_TREE_NODE: 'SET_OUTLINE_TREE_NODE',
    SET_OUTLINE_TREE_CURRENT_NODE: 'SET_OUTLINE_TREE_CURRENT_NODE',
    TOGGLE_EDIT_MODE: 'TOGGLE_EDIT_MODE',
    TOGGLE_POPUP: 'TOGGLE_POPUP',
    TOGGLE_TREE_MODE: 'TOGGLE_TREE_MODE',
    UPDATE_CHARACTERS: 'UPDATE_CHARACTERS'
};
